# Generated by Django 5.2.6 on 2025-12-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_category_remove_userprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
    ]
